
export const fakeProducts = [
    {
        "id": 1,
        "product_name": "Black Tea Classic",
        "description": " Premium loose leaf black tea",
        "product_price": 450,
        "amount": 15,
        "incart": 0,
        "instock": 1,
        "weight": 300,
        "category_id": 1
    },
    {
        "id": 2,
        "product_name": "English Breakfast",
        "description": " Full-bodied black tea blend",
        "product_price": 520,
        "amount": 20,
        "incart": 0,
        "instock": 1,
        "weight": 350,
        "category_id": 1
    },
    {
        "id": 3,
        "product_name": "Assam Harmony",
        "description": " Single estate loose leaf black tea",
        "product_price": 580,
        "amount": 18,
        "incart": 0,
        "instock": 1,
        "weight": 250,
        "category_id": 1
    },
    {
        "id": 4,
        "product_name": "Earl Grey Reserve",
        "description": " Black tea with bergamot essence",
        "product_price": 650,
        "amount": 22,
        "incart": 0,
        "instock": 1,
        "weight": 400,
        "category_id": 1
    },
    {
        "id": 5,
        "product_name": "Keemun Imperial",
        "description": " Chinese black tea with a sweet aroma",
        "product_price": 480,
        "amount": 16,
        "incart": 0,
        "instock": 1,
        "weight": 300,
        "category_id": 1
    },
    {
        "id": 6,
        "product_name": "Green Tea Delight",
        "description": " Fresh loose leaf green tea",
        "product_price": 400,
        "amount": 15,
        "incart": 0,
        "instock": 1,
        "weight": 250,
        "category_id": 2
    },
    {
        "id": 7,
        "product_name": "Sencha Supreme",
        "description": " Japanese green tea",
        "product_price": 520,
        "amount": 18,
        "incart": 0,
        "instock": 1,
        "weight": 300,
        "category_id": 2
    },
    {
        "id": 8,
        "product_name": "Dragonwell Reserve",
        "description": " Chinese green tea with chestnut flavor",
        "product_price": 600,
        "amount": 20,
        "incart": 0,
        "instock": 1,
        "weight": 350,
        "category_id": 2
    },
    {
        "id": 9,
        "product_name": "Jasmine Pearls",
        "description": " Green tea scented with jasmine flowers",
        "product_price": 480,
        "amount": 16,
        "incart": 0,
        "instock": 1,
        "weight": 250,
        "category_id": 2
    },
    {
        "id": 10,
        "product_name": "Moroccan Mint",
        "description": " Green tea with mint leaves",
        "product_price": 450,
        "amount": 15,
        "incart": 0,
        "instock": 1,
        "weight": 300,
        "category_id": 2
    },
    {
        "id": 11,
        "product_name": "White Tea Elegance",
        "description": " Delicate loose leaf white tea",
        "product_price": 550,
        "amount": 20,
        "incart": 0,
        "instock": 1,
        "weight": 250,
        "category_id": 3
    },
    {
        "id": 12,
        "product_name": "Silver Needle",
        "description": " Premium white tea buds",
        "product_price": 680,
        "amount": 25,
        "incart": 0,
        "instock": 1,
        "weight": 350,
        "category_id": 3
    },
    {
        "id": 13,
        "product_name": "Bai Mu Dan",
        "description": " White peony tea with floral notes",
        "product_price": 600,
        "amount": 22,
        "incart": 0,
        "instock": 1,
        "weight": 300,
        "category_id": 3
    },
    {
        "id": 14,
        "product_name": "Snow Dragon",
        "description": " Rare white tea from Fujian",
        "product_price": 720,
        "amount": 28,
        "incart": 0,
        "instock": 1,
        "weight": 400,
        "category_id": 3
    },
    {
        "id": 15,
        "product_name": "White Peony Reserve",
        "description": " White tea with a hint of peach",
        "product_price": 650,
        "amount": 24,
        "incart": 0,
        "instock": 1,
        "weight": 350,
        "category_id": 3
    },
    {
        "id": 16,
        "product_name": "Chai Sensation",
        "description": " Spiced black tea blend",
        "product_price": 480,
        "amount": 18,
        "incart": 0,
        "instock": 1,
        "weight": 250,
        "category_id": 4
    },
    {
        "id": 17,
        "product_name": "Oolong Harmony",
        "description": " Traditional Chinese oolong tea",
        "product_price": 600,
        "amount": 20,
        "incart": 0,
        "instock": 1,
        "weight": 300,
        "category_id": 4
    },
    {
        "id": 18,
        "product_name": "Pu-erh Majesty",
        "description": " Aged fermented tea from Yunnan",
        "product_price": 750,
        "amount": 25,
        "incart": 0,
        "instock": 1,
        "weight": 400,
        "category_id": 4
    },
    {
        "id": 19,
        "product_name": "Darjeeling Dream",
        "description": " Indian black tea with muscatel notes",
        "product_price": 580,
        "amount": 22,
        "incart": 0,
        "instock": 1,
        "weight": 350,
        "category_id": 4
    },
    {
        "id": 20,
        "product_name": "Matcha Magic",
        "description": " Japanese powdered green tea",
        "product_price": 680,
        "amount": 28,
        "incart": 0,
        "instock": 1,
        "weight": 350,
        "category_id": 4
    },
    {
        "id": 21,
        "product_name": "Chamomile Bliss",
        "description": " Calming herbal tea",
        "product_price": 450,
        "amount": 15,
        "incart": 0,
        "instock": 1,
        "weight": 250,
        "category_id": 5
    },
    {
        "id": 22,
        "product_name": "Peppermint Burst",
        "description": " Refreshing mint herbal tea",
        "product_price": 400,
        "amount": 18,
        "incart": 0,
        "instock": 1,
        "weight": 300,
        "category_id": 5
    },
    {
        "id": 23,
        "product_name": "Lavender Serenity",
        "description": " Floral herbal blend with lavender",
        "product_price": 520,
        "amount": 20,
        "incart": 0,
        "instock": 1,
        "weight": 350,
        "category_id": 5
    },
    {
        "id": 24,
        "product_name": "Rooibos Sunset",
        "description": " South African red tea",
        "product_price": 480,
        "amount": 16,
        "incart": 0,
        "instock": 1,
        "weight": 300,
        "category_id": 5
    },
    {
        "id": 25,
        "product_name": "Hibiscus Delight",
        "description": " Fruity hibiscus herbal tea",
        "product_price": 550,
        "amount": 22,
        "incart": 0,
        "instock": 1,
        "weight": 350,
        "category_id": 5
    },
    {
        "id": 26,
        "product_name": "Teapot Elegance",
        "description": " White porcelain teapot",
        "product_price": 3500,
        "amount": 10,
        "incart": 0,
        "instock": 1,
        "weight": 800,
        "category_id": 6
    },
    {
        "id": 27,
        "product_name": "Japanese Kyusu",
        "description": " Traditional clay teapot",
        "product_price": 4200,
        "amount": 12,
        "incart": 0,
        "instock": 1,
        "weight": 1000,
        "category_id": 6
    },
    {
        "id": 28,
        "product_name": "Cast Iron Tetsubin",
        "description": " Japanese iron teapot",
        "product_price": 4800,
        "amount": 15,
        "incart": 0,
        "instock": 1,
        "weight": 1200,
        "category_id": 6
    },
    {
        "id": 29,
        "product_name": "Glass Teapot Harmony",
        "description": " Modern glass teapot",
        "product_price": 3200,
        "amount": 8,
        "incart": 0,
        "instock": 1,
        "weight": 600,
        "category_id": 6
    },
    {
        "id": 30,
        "product_name": "Ceramic Gaiwan",
        "description": " Chinese lidded bowl for tea",
        "product_price": 3800,
        "amount": 10,
        "incart": 0,
        "instock": 1,
        "weight": 800,
        "category_id": 6
    }
]